# Generated by Django 4.2.1 on 2023-06-06 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('printed', 'Printed')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.society'),
        ),
    ]
